# Use the official Python image as the base
FROM python:3.8-slim

# Set the working directory inside the container
WORKDIR /app

COPY . .

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

RUN flask db upgrade

# Expose the port the app runs on
EXPOSE 5000

# Set environment variables
ENV FLASK_APP=rentcar.py

# Mount the code directory as a volume
VOLUME ["/app"]

# Start the application
CMD ["flask", "run", "--host", "0.0.0.0"]
