"""bussinesses table

Revision ID: 13422be4d293
Revises: 3747d0a882d9
Create Date: 2023-08-14 09:50:35.282249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13422be4d293'
down_revision = '3747d0a882d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business')
    # ### end Alembic commands ###
